apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vm-normal-user
  namespace: for-replacement
  annotations:
    # Ensures that this resource will be applied after the namespace
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    kubevirt.io: ""
rules:

  # Generic: namespace access
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
  
  # Generic: visibility on Ocp projects
  - apiGroups:
      - project.openshift.io
    resources:
      - projects
    verbs:
      - get
      - list

  # Virt: Console access
  - apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachineinstances/console
      - virtualmachineinstances/vnc
    verbs:
      - get

  # Virt: VM Power on/off
  - apiGroups: 
      - kubevirt.io
    resources:
      - virtualmachines/start
      - virtualmachines/stop
      - virtualmachines/restart
    verbs:
      - update

  # Virt: Snapshot & restore
  - apiGroups:
      - snapshot.kubevirt.io
    resources:
      - virtualmachinesnapshots
      - virtualmachinerestores
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  
  # Virt: native Kubernetes resources for snapshot
  - apiGroups:
    - snapshot.storage.k8s.io
    resources:
    - volumesnapshots
    verbs:
    - get
    - list
    - watch